### ISSUE TITLE
Does this step support Android apk's?

### ISSUE THREAD

**Issue by mrmartineau** [appaloosa-store/bitrise_appalossa#2]
The readme here says this:
> Appaloosa Store enables to test & deploy your iOS, Android and Windows phone apps.

But the Bitrise workflow step only mentions IPA files. Does the step support apks? If it does, is there anything else that needs to be done if an apk is being used?

**Comment by jeremybdk** [comment]
It should support APKs just replace the IPA_PATH with your APK_PATH.

We haven't tried with APKs but I believe it should work. Let us know if you have any issues we'll take a look.

**Comment by mrmartineau** [comment]
Hi @jeremybdk, I can confirm it does work. Can you change the copy within the step?

**Comment by jeremybdk** [comment]
What do you mean by copy within the step ?

**Comment by mrmartineau** [comment]
The copy (text content) in the Bitrise interface exclusively refers to iOS and ipa files. It should be made more general to include the other platforms and file types that Appaloosa supports. See [this screengrab](https://www.evernote.com/l/AA97trRqvDJIhZMfU40SZAayfFEbxHE0u_MB/image.png)

**Comment by jeremybdk** [comment]
Sure you are totally right, we'll improve that soon !

Thanks for your feedback,

If you need anything or have feedback please let us know !
